import{a as L,S as b,i as l}from"./assets/vendor-xpOxgMII.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const w="54348410-ddd68c2f741a9577a6bd8a40b",S="https://pixabay.com/api/";async function v(t,r){return(await L.get(S,{params:{key:w,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:r}})).data}const f=document.querySelector(".gallery"),m=document.querySelector(".loader"),p=document.querySelector(".load-more"),q=new b(".gallery a",{captionsData:"alt",captionDelay:250});function M(t){const r=t.map(({webformatURL:s,largeImageURL:a,tags:e,likes:o,views:i,comments:y,downloads:g})=>`
      <li class="gallery-item">
        <a href="${a}">
          <img src="${s}" alt="${e}" />
        </a>
        <div class="info">
          <p><b>Likes</b> ${o}</p>
          <p><b>Views</b> ${i}</p>
          <p><b>Comments</b> ${y}</p>
          <p><b>Downloads</b> ${g}</p>
        </div>
      </li>
    `).join("");f.insertAdjacentHTML("beforeend",r),q.refresh()}function P(){f.innerHTML=""}function $(){m.classList.remove("is-hidden")}function B(){m.classList.add("is-hidden")}function E(){p.classList.remove("is-hidden")}function c(){p.classList.add("is-hidden")}const O=document.querySelector(".form"),R=document.querySelector(".load-more"),x=document.querySelector(".gallery");let d="",n=1,u=0;const A=15;O.addEventListener("submit",_);R.addEventListener("click",C);async function _(t){t.preventDefault(),d=t.target.elements["search-text"].value.trim(),n=1,u=0,P(),c(),d&&await h()}async function C(){n+=1,await h()}async function h(){try{$();const t=await v(d,n);if(t.hits.length===0&&n===1){c(),l.error({message:"Sorry, there are no images matching your search query.",position:"topRight"});return}n===1&&(u=Math.ceil(t.totalHits/A)),M(t.hits),n>=u?(c(),l.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):E(),n>1&&D()}catch(t){c(),l.error({message:"Something went wrong. Please try again.",position:"topRight"}),console.error(t)}finally{B()}}function D(){const t=x.firstElementChild;if(!t)return;const{height:r}=t.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
